# Generated by Django 5.1.2 on 2024-10-26 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0002_alter_accommodation_accommodation_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='description',
        ),
    ]
