# Generated by Django 5.1.2 on 2024-10-26 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accomodation', '0002_alter_accommodation_accommodation_type_and_more'),
        ('tours', '0001_initial'),
        ('users', '0005_alter_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('tour_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payment_status', models.CharField(max_length=1)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accomodation.accommodation')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.tour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
        ),
    ]
